### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file 

### ISSUE THREAD

**Issue by aenulfi3** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#17]
got this error WHEN running python main.pyc

**Comment by TG-ToolsFree** [comment]
You need to update your Python.
If you have already installed the newest version, follow these steps to check it:
1. Open cmd
2. Type this command: _python --version_
3. Type this command: _python3 --version_

If the newest Python version is installed under the python3 command, then use the **python3** command instead of **python**
