### ISSUE TITLE
Can I get ban from telegram because using this?

### ISSUE THREAD

**Issue by JohanChungus** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#30]

**Comment by kiko19871312** [comment]
I think you are not the only one bro. I lost over 100 accounts because using this script. But it start happening few days ago, before that everything was working fine. Now, I'm getting banned with ANY profile I log in to the script, I've wasted many accounts and I'm waiting for developer to try help me resolve this problem.

**Comment by amiiko** [comment]
you are not alone guys i am getting banned too i have try with too many new ip address and pc and accounts. so far i lost 9 accounts.

please contact me on telegram and lets figure this out together @amanuel_kev

**Comment by TG-ToolsFree** [comment]
This is a problem of Telegram changing their limits. It is dynamic, which means you will not get the same result everytime. If you get banned like that, you most likely got flagged. Either your ip address, your mac address or even maybe the country you live in could make problems. If the limit of Telegram is dynamic, which it is, then you will need dynamic solutions with dynamic changes. Use different country area codes, use different api's, use different ip's and so on...
